#!/bin/sh
 
# PROVIDE: freenas_storj
 
. /etc/rc.subr
 
name="freenas_storj"
rcvar=`set_rcvar`
start_cmd="freenas_storj_start"
stop_cmd=":"
 
load_rc_config $name
 
myscript_start()
{
    if checkyesno ${rcvar}; then
	echo "Script $name started!"
    fi
}
 
run_rc_command "$1"
